### ISSUE TITLE
Great app!

### ISSUE THREAD

**Issue by sasha-id** [jagadeesh-k-2802/password-manager-compose#1]
I was looking for open-source secure offline pass manager, and found your app. Really nice, better than anything I could find! 🙏

**Comment by jagadeesh-k-2802** [comment]
Your kind words are much appreciated! It's wonderful to hear that you're enjoying the app and finding it useful. I'll be closing this issue now, but please feel free to reach out to me via email if you have any more questions or feedback down the line.
